{"_id":"6f287750-b255-11ec-9070-750395a7028e","postId":"2022_02_cancellation-1-overview-f578fde1-7dc4-3df5-88ec-107dca6b348e","postUri":"https://blog.stephencleary.com/2022/02/cancellation-1-overview.html","replyTo":"d4494940-a2d1-11ec-a84c-8facc0185c43","authorEmailEncrypted":"CVNfDSNugCf/KhtbzqoYLUkNT3jr/bzzULa+1hIprm3NgCgIyjkov9hBYrmAPJKxJ4ydcZjxZTbqXkJT93rALT/WzUaCHaziKLAu1LZsfeLpbWqsZsRcq8/t+l/C1j36xQAwdRZBm4llumk5qbzK9pispliKPkD6h+8P0Y6ZmjFngzNEpaeuKjlnYoFghA/Txfhn6705OB1EEl/lGVztju+kxAwxdUxAw4pw8BqKNckVSZGIMJDX6Qu7lMwe+Hp3jeqIRRX/XAnXqFlWFzxRE7KyJ/TuGVM9wL29LRPFXMwZVeNg5g8hzf+7Z/CB2X/tlDGbrdrpFS5zuX40FyD9Bea8uEnv7+ZvQ0ouRl2nqzeq3hFzFXCNw0V7Xng55vEKxe7VqnD2l87UpljuodUpED6Xy2RBrQoRU/QlJ+UUnZbIpI8+jAfmR7rWkDT7hJd1HyX+BDVHR8OGzRtWmxUv0ma8cH0El7yFV9NVzdSVY6z+uzv0yE+kOf9OPBTuP67zzqkAFJjhUpKzBd2CoNovAW/sd6bgGhipbkXut3s9ZbNo3FC3r7usGwq463BlIo0tLL5y1rML1WkOazK49Z5KhKjvvqrGqeNFgEdRWPIbK6m/uvnHXgtraDr3xnvbtKxrF70GslhmPG3ZSRFrLD31ZwwN38mOlqid/91Euqbo4vo=","authorEmailMD5":"beb9e59cf6b8f056b0762960f549de29","authorName":"Milos","authorUri":"","message":"Hello Stephen,<br/>\r\nmy experience is that this behavior is not related to the explicit use of continuations. Even if you await task constructed this way without passing cancellation token the resulting status is still `Faulted`, which may be a little surprising at first.<br/>\r\nM.\r\n\r\n```csharp\r\nasync Task Main()\r\n{\r\n\tusing var cts = new CancellationTokenSource(250);\r\n\tvar cancellationToken = cts.Token;\r\n\tTask? task = null;\r\n\t\r\n\ttry\r\n\t{\t\r\n\t\ttask = Task.Run(() =>\r\n\t\t{\r\n\t\t\tThread.Sleep(500);\r\n\t\t\tcancellationToken.ThrowIfCancellationRequested();\r\n\t\t}/*, cancellationToken*/);\r\n\r\n\t\tawait task;\r\n\t}\r\n\tcatch (OperationCanceledException)\r\n\t{\r\n\t\ttask?.Status.Dump(\"t.Status\");\r\n\t}\r\n}\r\n```\r\n\r\n```\r\nt.Status\r\nFaulted\r\n```","date":"2022-04-02T07:20:55.153Z"}