{"_id":"fe0ae403-758d-3ae0-8ab4-10c73fe47a28","authorName":"Stephen Cleary","authorEmailEncrypted":"","authorEmailMD5":"3db7b6e14d9da42751e4bab03bc4d034","authorUri":"https://stephencleary.com/","authorUserId":"","authorFallbackAvatar":"","message":"Yes, you are correct. Sorry, I read through that code too quickly and missed that. If the try/catch is inside the Task.Run, then it will be on a thread pool thread. You can move the try/catch to be outside the Task.Run, and then it will be on the UI thread:\r\n\r\nprivate async Task MethodThatReturnsATask()  \r\n{  \r\ntry  \r\n{  \r\nawait Task.Run(() =>  \r\n{  \r\n// fetch data from service  \r\n});  \r\n}  \r\ncatch (Exception e)  \r\n{  \r\nstring err = \"Cannot get data\";  \r\nLogger.Error(err, e);  \r\n_dialogService.ShowError(e);  \r\n}  \r\n}","postId":"2014_04_announcement-msdn-async-mvvm-articles-b2165e1d-7e99-386d-b481-ed64583f3ab7","replyTo":"b71979cc-5d4b-357e-8bbc-7b9aab65ff31","date":"2017-03-13T13:08:35Z","timestamp":1489410515}