{"_id":"fe0ae403-758d-3ae0-8ab4-10c73fe47a28","authorName":"Stephen Cleary","authorEmailEncrypted":"bkWY4GM20RnyckjE5OxCA41qlMMQuyqVU4goFHTQZcT/lVbOsgXsJmW5pEfgvQxUxaRFLketdwZ5SdO6TsiSP6J9vgj/Zp0QiuYUSMHzwgrcagicjau9FUWZjlKkRNC0nzE0NGXwaVUPCoIbtdQrNOkza6rY34i8czHeLeif6Pdqv1hG71WSolIVeuX9wsa34gv3h8Y3T3lR1gjJXz9Y2kXT0SwjAzyiq7JQFclvfM+nmRqIb/HQCkMF0O94YhmB/0tdF72HwDv3CS+zfBGnN/vR5GSeHiEA402Ct09B9OfIDex8HulV50UM6DL/EM51wRIcWCD5XaJBJgNsmLJhCTMkW57mdjOZURtom99WfKBZbhBZ6vXfLqSoN+gKd15JnHagqMcmh8hwVBz1KZgqrvxeSCCYVNHpb0kSP/YODg94rECRF639lopxdFhecFKMqKL/Ny0UQ7LU4LkP42TjyqkaQlIP2R7iiWHYXdzOY2boR2V96yNCmVQDXyrb/HstJWh0g1rmcLz76sbRO1Zj9rwAUpy2CQtcyXQiPWzp3Td38wiOA3x3pUeN4aMH1zbP3468g1hr02jq+QzJO//v/3UwvFjqohwI1DkeaJ8RYtGspavdtseQ6zMqGz35W0r/rElH2YiG4mUTLCXnW3lu10EZYGC0T/xYtpinMVYIvq4=","authorEmailMD5":"28dde5772b48c92e08b8050411aa5ba8","message":"Yes, you are correct. Sorry, I read through that code too quickly and missed that. If the try/catch is inside the Task.Run, then it will be on a thread pool thread. You can move the try/catch to be outside the Task.Run, and then it will be on the UI thread:\r\n\r\nprivate async Task MethodThatReturnsATask()  \r\n{  \r\ntry  \r\n{  \r\nawait Task.Run(() =>  \r\n{  \r\n// fetch data from service  \r\n});  \r\n}  \r\ncatch (Exception e)  \r\n{  \r\nstring err = \"Cannot get data\";  \r\nLogger.Error(err, e);  \r\n_dialogService.ShowError(e);  \r\n}  \r\n}","postId":"2014_04_announcement-msdn-async-mvvm-articles-b2165e1d-7e99-386d-b481-ed64583f3ab7","replyTo":"b71979cc-5d4b-357e-8bbc-7b9aab65ff31","date":"2017-03-13T13:08:35Z","timestamp":1489410515,"authorUserId":"disqus:stephen_cleary"}