{"_id":"fe0ae403-758d-3ae0-8ab4-10c73fe47a28","authorName":"Stephen Cleary","authorEmailEncrypted":"kp3z2IhcVyLktPh49aI1ithDAoMuyGMJ0ouJ4Lg7NSF2gAYPr5ob7VMQAQxuuTyo1DP8zVqFLd09S83nCdW4FXERWQ2wWr8/HQ6CUXO9NG/2SgkY7MlVPLq5Fo3U5c883V4qSiJfahe87D96kftRDR9DxbFS606knCeaFmoiA2XvujSTVFjvR+I337W94wh6gjwnvoyOr4G60DjGTQvBVOcJ2tgoC+mXyKakaSYnONuoeo94D7Bl2yFVsc1WsdOf59IwuLiNoqYST7GKG0cw5FQ8yBtWA+heAVU3VZQvdDpcGg+dxQB3YMbv8QTFl61yDFmLhS3f5yYcUmhRaJzyrI+hHpEIh20p2faRHuzrNNWPVbJImexOGkYm0y5skvCNmm8Av705XxQ24XBYIGb91faCrQZyR8g5T3fd0+JgaJHzETvnaTWc+VxvOoj7P3ez9TUhWa2EIsnJpwzM2YYXQKCeRS6dYiZBtzPPVoLZ+eYT3qtcGAXFlrnwAu7NEOQry64DNsb4KKs/Vng0CcHgTf1qiFzslJ3dCVr0J9THc4ibS8ke1fNnixiLyw+0Y+KvTbG7gQG8deY13QBNIDALWKl+k+RZrGUK3tMiNyvpnr3NR5L++TVr29vLS58zx0wt31HGzGKND9baql3qWCk1OtTcdxBpzUmea90sTh4bs6Y=","authorEmailMD5":"ad2250182ff26a84dda974e50cd94382","authorUri":"","authorUserId":"disqus:stephen_cleary","message":"Yes, you are correct. Sorry, I read through that code too quickly and missed that. If the try/catch is inside the Task.Run, then it will be on a thread pool thread. You can move the try/catch to be outside the Task.Run, and then it will be on the UI thread:\r\n\r\nprivate async Task MethodThatReturnsATask()  \r\n{  \r\ntry  \r\n{  \r\nawait Task.Run(() =>  \r\n{  \r\n// fetch data from service  \r\n});  \r\n}  \r\ncatch (Exception e)  \r\n{  \r\nstring err = \"Cannot get data\";  \r\nLogger.Error(err, e);  \r\n_dialogService.ShowError(e);  \r\n}  \r\n}","postId":"2014_04_announcement-msdn-async-mvvm-articles-b2165e1d-7e99-386d-b481-ed64583f3ab7","replyTo":"b71979cc-5d4b-357e-8bbc-7b9aab65ff31","date":"2017-03-13T13:08:35Z","timestamp":1489410515}