{"_id":"fe0ae403-758d-3ae0-8ab4-10c73fe47a28","authorName":"Stephen Cleary","authorEmailEncrypted":"XV25soh7A3FAAeqpu0CSudXGap0laHQ92hjPSCtUuJW/Pd9kZvhBHdJgI4AAqYUO25oAJ0lt7D23xVelUtVmbOanE5nDkleAhOgRBYHTB78wFCY92HRTvhTyk/pVSgD/2KKkHfpGjjX3X5uJyQ8tOsQiTJEPP93lCVt4hnvaIgXZfa74aWerkf/VTZLMHWHEcKkGNzQ+8q6rq5PKU1JDr34HwKosqOpB2JhRavzY4ajjiAS4xQg1To0nwmT59LNfem4wRdibO99A2xRln0kTEtcqS82/Kl7CKNouOisDc+xNycq1Nl3zUEOF6fx3mfEuI1FVF2Lb/QEHKijErWIWNpq6/ey8uKEPELlztxlj7f92LO8M8RX3JoRrZvGbfvNTnGWuPJKhqTM4nK7NlubAiQRETsvWdY3dypiC217eRG2Z8z6qVOZub0bItgGnEKYrrgsdWbDhpD9TNSlLeYxmH18zhh4mrou0jAE3DOzeDRzyPE1GkSkJLbTu9WS1CcmkYcO8mwsaF0oA/NudQeGMJ+T2+OOpaNPeEP6ex57t2C/QPPv3Cy0ln8XZhScrj7Db9ydgq1MpmeaJO8+W2qYlNqY+wi+nnCoR4SfBWQySFilUpy6g6A3UqpGwpn/mXkCGoFmNqESiX0pPEsYVZZy6ikW/aXKzY3xryilhZevqey8=","authorEmailMD5":"ad2250182ff26a84dda974e50cd94382","message":"Yes, you are correct. Sorry, I read through that code too quickly and missed that. If the try/catch is inside the Task.Run, then it will be on a thread pool thread. You can move the try/catch to be outside the Task.Run, and then it will be on the UI thread:\r\n\r\nprivate async Task MethodThatReturnsATask()  \r\n{  \r\ntry  \r\n{  \r\nawait Task.Run(() =>  \r\n{  \r\n// fetch data from service  \r\n});  \r\n}  \r\ncatch (Exception e)  \r\n{  \r\nstring err = \"Cannot get data\";  \r\nLogger.Error(err, e);  \r\n_dialogService.ShowError(e);  \r\n}  \r\n}","postId":"2014_04_announcement-msdn-async-mvvm-articles-b2165e1d-7e99-386d-b481-ed64583f3ab7","replyTo":"b71979cc-5d4b-357e-8bbc-7b9aab65ff31","date":"2017-03-13T13:08:35Z","timestamp":1489410515,"authorUserId":"disqus:stephen_cleary"}