{"_id":"9d651ef0-abe2-11ea-b64e-ed8d1e1942af","postId":"2020_06_a-new-pattern-for-exception-logging-727f531a-2b21-3b7a-ba16-032c960fc67a","postUri":"https://blog.stephencleary.com/2020/06/a-new-pattern-for-exception-logging.html?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+NitoPrograms+%28Nito+Programs%29","replyTo":"","authorEmailEncrypted":"WcIOkkPD5Uxmo2Pfqu9BNmsSgsqAL3bY/0BdHSBiG3o1lUAXONm90DV6qDRytNm2DKRTbhDhwSGJWWk13k7TP6VmSr+dZ+skn9bVGI20svw2o0AQjASJmv5xvhVCDkci5qxP3rRGGHkb0yDiSXZqIpEQbWVudoh3g3G7++SEuvmmMJ29FhFVDNc+oTeyNQkIsh/dzI8Ai02RC/oicawWvVXcw18mOiGX1sny4bNACvn+bhvpDOZlqmi/h4FfcyhofhXlTOT6c7uQJUOZkWrqrVnptcTjDO3fcran3UevpsqEDj1atMb446J1ZcTKixfEB/zCvGrSgsOmwBOqqLNga6TNB5mgRb+ferW+z+pkLJR9+OK5ltR9kiHEj3JY8dxDwrBAl4LqPeH4AJehAwTYDo0KOrr40xIzPNg56hfCsxr+xsFx9Okzo2SHo07JFFf8iPhgb5sTtowmyzelVEH1AZuIz4Uj6a+f0ajMgyNLEjadQ7LaNtjpKvxl4iOSoGonW9Ygn+aXJlZkrv/knEB1QT5aQy69BiCU2oOfrCtnFOEs7VFfrQgRhvppuzP0jPZa7HZufmYl3mr1ENVBX1d1ealEbVezVWm5GsmOqIFOZdNwubyvO0l5JXtHJw6J17SfxymooUTGYt3KDfPxb6fsI8/QPBaNxGxJpuJC6NULVyY=","authorEmailMD5":"05f5df46fc12fbf8299f33b474f1e418","authorName":"Viktor Nikolayev","authorUri":"","message":"Hey!\r\nThanks for the article.\r\n\r\nWhat if we have an `await` statement inside `try-catch` block?.\r\n\r\nAfaik context won't be preserved in that case.","date":"2020-06-11T12:53:58.273Z"}