{"_id":"53a99950-9a5a-11eb-a59b-69a8b94b22f1","postId":"2020_06_a-new-pattern-for-exception-logging-727f531a-2b21-3b7a-ba16-032c960fc67a","postUri":"https://blog.stephencleary.com/2020/06/a-new-pattern-for-exception-logging.html","replyTo":"","authorEmailEncrypted":"","authorEmailMD5":"","authorName":"Enrico","authorUri":"","message":"Is it really necessary the `throw` instruction inside of the `catch` block when the `False` helper method is used ? \r\n\r\nI mean for sure it makes the code clearer to a reader and sometimes it is needed to make the compiler happy (when the methods holding the code returns something), but for methods returning `void` or `Task` it seems to be redundant (if my understanding of the pattern is correct).","date":"2021-04-11T00:10:30.932Z"}