{"_id":"0b02443e-494d-3ddd-ac59-4bbed42be0b7","authorName":"esmark2479","authorEmailEncrypted":"r5jLV1sJCPGbmOPdfno6WatrJRKg2Jz6kAk1cTmaU+ivMlcIZja93IufrSzHnrDAqHVMSXlHHAjxbPV9N3QdwCIKwPVWZfA812tkzdMiwMEbGLaJdgtFms+6zjjPwc0eDxmDDkdjwtSvgvz5wmeiT2JZrLXmCEawCnWATmMSlaRX/pd1fDmgoXIM/q7FLflJeFKCGtloZJCDKYXDSdsIcsrlBoqcJVmQkMTYru6Td/umIy5tTlzkrLSkDg1lQKU8eLKHYu7DYL3af7pakODUY1p4b27XY+M+vnyGtWYNOzvPYJ9emT/Lh2HiUa2dxIzTZUCBBjAocsVGsCwWBfH9X6iOBcDap1FU3uQzDdJ1wGNvAw3Z5viedENGobcIrH4bRzqqabmlg4Fc9+jjZuDJX1AV52Rj3CAADkhAHHoe1s8LcBncOEWU01tMiArXl7jY63+9N9bMgQjQ4HrPGeyOT9nFqVW4R2uuHYRwxpO/Mkj3RLTXwdd3HGvrr63Cn4s7l6TbXr9pM5ww4PKEgafj88o1xlYOtHcJzshsGLNNfnEiwBSY7K93n+0SIllJmVSdUATmTBj7xzDtZrL4AWE6LSzhbaHZYR4yiNC45WxGI86+6x9agWM6BykfqrBruIHd1FD8JpfN+WKrDPGLpGLKGAlJnNSP6B8yqDvj905heY0=","authorEmailMD5":"a4bacff0e3fcad6ce19e387b4ed7e745","message":"In the section titled \"Asynch Composition\", in method DoOperationsConcurrentlyAsync, suppose you want to add a try-catch block. Would the try block need to wrap the statements that launch the three tasks as well as the line containing the Task.WhenAll() or is it only necessary to wrap Task.WhenAll? I would think all of it since one of the tasks could throw an exception before Task.WhenAll is invoked, but maybe the exception isn't propagated outside of the task until a Task.Wait or Task.WhenAll is invoked.","postId":"2012_02_async-and-await-bb1cce3d-e706-3ecf-ab89-6f7945ef7d0f","replyTo":"","date":"2018-02-20T01:49:39Z","timestamp":1519091379,"authorUserId":"disqus:esmark2479"}