[{"_id":"413641f0-bc2f-3cbc-9215-8c71c395da91","authorName":"Jonathan Allen","authorEmailEncrypted":"","authorEmailMD5":"","message":"Thanks! I was wondering why my \"failing\" tests weren't actually failing.","postId":"2012_02_async-unit-tests-part-1-wrong-way-36b6b297-8f03-3340-b0a6-10e349ad0849","replyTo":"","date":"2013-01-12T13:53:19Z","timestamp":1357998799,"authorUserId":""},{"_id":"9072648b-af30-3b8f-8259-c7bce8512900","authorName":"Anonymous","authorEmailEncrypted":"","authorEmailMD5":"","message":"Errr: It seems like there are two problems here, *none* of which are related to async.  \r\n\r\n1. Using 'async void' is just plain wrong here.  \r\nRefer: [http://msdn.microsoft.com/e...](http://msdn.microsoft.com/en-us/library/vstudio/hh156513.aspx \"http://msdn.microsoft.com/en-us/library/vstudio/hh156513.aspx\")  \r\n - \"The caller of a void-returning async method can't await it and can't catch exceptions that the method throws.\"  \r\n\r\n2. ExpectedExceptionAttribute isn't a good solution here, or anywhere.  \r\nThe issue with unwrapping the AggregateException again isn't anything to do with async, it's just that ExpectedException doesn't allow you to verify the InnerException. Just write a helper function to catch the exception for you, and then verify it properly using normal asserts!.","postId":"2012_02_async-unit-tests-part-1-wrong-way-36b6b297-8f03-3340-b0a6-10e349ad0849","replyTo":"","date":"2013-01-14T07:42:32Z","timestamp":1358149352,"authorUserId":""},{"_id":"a8f2496e-33e7-36ec-bb0c-f128aae9f846","authorName":"Stephen Cleary","authorEmailEncrypted":"fEYMhRBCrIqLXBRSgZwO+4HA62I/f9qYw0saZQmt6hVH5BXpb0YIpM/HvtRaaPQYYgHT1lM9hnEyy1+U8fW82lnZLceW/Sx5P2fpOKvKiMEkBI9hKOqVVOcdRkugjPCy7jt3zLJIJMTrCPJMMv7OpEdMUoojNYCWmh3sExCCDaLtS+teaUpPxUasfjeITwgBEq95a6nDqQTcWIWx4fsOUHqS3ek27WuCjWaJDp85Pm7rUNr6bf6QMc+fT1TPq32JJ/j4qoEmZqnh8+FIF4oOyjUgBklmdjcGNjOvz48qUoLgfYEIoRdDrOauyOjjdiTblJV11LNTQ6M3vmfKm8iED5k522vgn03Z/78CgdqS4DqSmOFydVPE8Nc0Tp/rK0eTfdXMvba5urcyYfFYk0K6nLHDjqvGfMevW09nmwjU6Qm2WhX743n2R2sj3eF0lnm2waTq6h8OmByfypILrCwMycH5QbXa6xap9SWF0iu9XGmRB7DlBz1rWa94KeEuPAGJI4lQspJuOxhq/13Uwf+WDmzlQhwlgvfwgf/iFF2aLjHhOTw1ycFCfqrKd1gioOrMPxDB9RlCsRZ6LOprZF+rNsY1rraMzhyFATL57FB13pPA+d4CXI2eO1BS5OUiojUYRNiggptCOGMm2R1VXA9eaw4m2ljqbJsaQvKpXx9f3Bg=","authorEmailMD5":"ad2250182ff26a84dda974e50cd94382","message":"At the time this blog post was written (when only VS2010 had been released), \"async Task\" was not an option for unit tests. BTW, it is possible to provide a context for async void methods and both wait for them and retrieve their exceptions; this is how nUnit supports async void unit tests.  \r\n\r\nI agree with your comment re ExpectedExceptionAttribute. I use and recommend a ThrowsAsync method for checking exceptions on async methods. I used ExpectedExceptionAttribute examples in this blog post because that's Microsoft's recommendation and the approach most MSTest users are familiar with.","postId":"2012_02_async-unit-tests-part-1-wrong-way-36b6b297-8f03-3340-b0a6-10e349ad0849","replyTo":"","date":"2013-01-14T17:55:25Z","timestamp":1358186125,"authorUserId":""},{"_id":"54131b57-6e48-347a-a065-b565d4341459","authorName":"Dave Schinkel","authorEmailEncrypted":"","authorEmailMD5":"","message":"Not coding without tests is NOT extreme. It's how you get shit done and how our trade will and is developing into and how we should be developing software. Test Driven is effective, it's not theory and if you adhere to principals and see what it can do, you never question doing tests, you ALWAYS do tests. [http://blog.8thlight.com/er...](http://blog.8thlight.com/eric-smith/2013/04/08/we-are-principled-6.html \"http://blog.8thlight.com/eric-smith/2013/04/08/we-are-principled-6.html\")","postId":"2012_02_async-unit-tests-part-1-wrong-way-36b6b297-8f03-3340-b0a6-10e349ad0849","replyTo":"","date":"2014-04-21T04:18:49Z","timestamp":1398053929,"authorUserId":""},{"_id":"c10074c4-5d61-38ae-9aa1-88aa7a86f47a","authorName":"Stephen Cleary","authorEmailEncrypted":"prIZHMKHMs04804bmNqUxhzbD7io7kLn25rHYWP5m692HQMYNGVYgvg7JuqRzA04OIdLjX3iGXeVmLrbbesQtgeFeG/20yiQ7NETVq4XaLWF8PPUGCzGU7WRm+KWGEXvtDDvdNHqqOZZnBMxpQXXcM+7ZHkRgUkhaHeCbDVvD26QrbipjvCQwPea66gHQYpbIbDD2t83w0XoBfyRXTWRRsmjo9aD45UBOAcSR2YRzAf9nmtZMNZrpyh+uSj61TDatVrfyYVFrGKc+SZ9i100xSk2yV8TWE/Fe0A3lmuBTb4PLGrTGuhRI491hYqenofGcCPcibIc1K2iUk6lTz4X9WMR7fypIiONx2PTbLJWCAQ4OoLDn7IKzOkTfY0uoZ5S5SQUi6AMpDCG01YjgnwEwKxmbkn5TkWa530xQTzu9aWSG942JL/auC8G49N5Wn4YYBLBxlMwQ6H8z56oRsd4lL5SEQfKIC4+CtwKw37M9+X/2adnAzdM8d+oPNYEuzRcQwrZpWAHhA2NOeRtcni/po1NpJ8W6kHhbwYEDNo+74uoQOFnpU5azTAXwzGGSbENgKUe7suWiJbf9WFMg5rf5hF4T8I99oasbfbpOrWqGqlK7F2ttfRT7TVgJtIfTYev65a5vOODSIgiF4vA0A2vfUvtBIKs49DPvV2vKIlOBrU=","authorEmailMD5":"ad2250182ff26a84dda974e50cd94382","message":"Agree to disagree. I read that blog post about a year ago.  \r\n\r\nThere are certain types of code such as domain objects and business rules that are very amenable to tests and are ideal for test-driven development. I would go so far as to say that there are entire applications (probably a majority of applications) that can be developed using TDD.  \r\n\r\nHowever, there are also other types of code such as low-level synchronization libraries that cannot be fully developed using test-driven development; at some point a deep understanding of race conditions and other multithreading concerns *must* guide the code development. TDD alone and unguided would result in subtle bugs.","postId":"2012_02_async-unit-tests-part-1-wrong-way-36b6b297-8f03-3340-b0a6-10e349ad0849","replyTo":"","date":"2014-04-21T05:52:14Z","timestamp":1398059534,"authorUserId":""},{"_id":"0816457d-1ebf-3136-b0d3-0c806cc18fec","authorName":"Dustin","authorEmailEncrypted":"GDnMCdTs/J1vlPg3dg4hg5wDpQ6w4T/UUGyEQ7fANA9nWK1C5c6JryAHTe5vMye0HfpsvMu/kBqWJNupvE8gtxdXXlKhrhvIOGqgGWOfI9TxV7wJfjsi4KOrPkTt2DpW06JFUMmYQKwjqwZnxRZweym3QQtH1YQN6st+QFRoVxiKj7V/PzcgWH6DR8nwdCoh0hNoS59YtsQsK92DgTie1Ngp/sprzUglSRNyQQHktiu55jrc+F+ufKl4Vw8jOxrAilbiUgf6yTAkVoyjOZvNZz6o0AY8n1G7sWnOH1lvj9hkdMQSdIYyAUFjYnu/GsmiPHQJUNiACVVRBUSo4FhI0MYsZ4pvSXCxAKIh3JTI2N+1e0ZviJx/lO+xWEUdJhB+YW3bOYIOqfIwrVoN+E+ffiaq4d/PKzpZW7kr4hUUp5JbtqC51h/Ieka59O13vkBYcUS4nkwkD8KnI/Jl23QKnYvEXk0BbM4Ll9Ui3qGjJcsAT5ymNDzINcg+nAb9ZZAq8FYxVfFqXWH+GH4Oo9WGKUl27pkAK/pzY6NliArPBc5p9Cr3A1eZ2ywbptkOkQeHuw2k2MZWhfa5OtC1Pm6izzwKyEvyu8prFT8vhb2OU2drNHUFY1EEwRWvHrYmUbe6Ac9/D7by4aR/7yfujvdrf/rvSiNciGU52cGxhmIsW94=","authorEmailMD5":"4071a791320e2c575e7e28323de11909","message":"Xamarin.iOS 7.2 release notes indicates async Test support: [http://developer.xamarin.co...](http://developer.xamarin.com/releases/ios/xamarin.ios_7/xamarin.ios_7.2/ \"http://developer.xamarin.com/releases/ios/xamarin.ios_7/xamarin.ios_7.2/\")\r\n\r\nJust tested this myself and I can now await things inside of a test case.","postId":"2012_02_async-unit-tests-part-1-wrong-way-36b6b297-8f03-3340-b0a6-10e349ad0849","replyTo":"","date":"2014-12-08T16:59:39Z","timestamp":1418057979,"authorUserId":""},{"_id":"46939aa1-12d7-30ad-9a30-da21f50cceb7","authorName":"Stephen Cleary","authorEmailEncrypted":"YXMh02NVmaPdpS9EfA27UX0/f8O1HidBEmvRbncN8Wl4SXs8Fp5yR6L+TpJ6kou4FdyptA6JrGJQYQydBWopMDCSg+dp+SSFvr9uD1WoQDFFvh/nXNbXu6d0wI7uwLcqo6+pEGFUgO7/R6siR+wVSJ2NkdeOJC675bP5YZ95d3kX69MzGVJGNy6bRjgk4q5/js6EE+Buy/Nfdr+Ahy8Uq4tElSUbOvcYt/+buNa0NXuNaTrYHOT9cN+HbFsyHwVoMd4bjU0JCzw4HF8UJqj6czqsYJmAAZhawzmCAhiv86bNsrCX3ywWr2aDRinz403ad5H+VwKPE8j/HYmd8H43Dy6/ekh9dUYCXRRg1m2RFHYodX/eAQY5fPqHXPf+F4VnPB7HupPj1lHPf1Ur9fDERq8sE4UJXipH2uoNec+lhIsODqX6saIVRsIOLnySW9N3MHbsQJPspxOYBjMqsykJwpL2U7ad1sPrhZWFTfiAahQK50G0ksH4JDK9QyIr0idWo37G66QdMFGj6Q74hg2ws8wrEtF41MCiQAS1f6KSD+Hz8hRdomR11ZhW5w7z9UtbGuch7qajNyZmQAxcZ4eD9YdMtm8RDlAVYw8kuPiwdaOovbnUFvH3LGiWy8ymJ+14KoubNfO3vYShVqd2214Oj0SK3BaIsQfmYyiEzNYdkh0=","authorEmailMD5":"ad2250182ff26a84dda974e50cd94382","message":"Good! This is something I've been bugging them about for a while... :)","postId":"2012_02_async-unit-tests-part-1-wrong-way-36b6b297-8f03-3340-b0a6-10e349ad0849","replyTo":"0816457d-1ebf-3136-b0d3-0c806cc18fec","date":"2014-12-08T19:08:14Z","timestamp":1418065694,"authorUserId":"disqus:stephen_cleary"}]